# Generated by Django 3.0.8 on 2020-09-24 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tác giả')),
                ('dateofBird', models.DateField(verbose_name='Năm sinh')),
                ('dateofDie', models.DateField(blank=True, null=True, verbose_name='Năm mất')),
                ('biography', models.TextField(verbose_name='Tiểu sử tác giả')),
                ('home_town', models.TextField(max_length=300, verbose_name='Quê quán')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên truyện')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã truyện')),
                ('numberChap', models.IntegerField(default=0, verbose_name='Số chương')),
                ('content_sumary', models.TextField(verbose_name='Tóm tắt truyện')),
                ('image', models.ImageField(upload_to='static/image', verbose_name='Ảnh bìa')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Author', verbose_name='Tác giả')),
            ],
        ),
        migrations.CreateModel(
            name='Chap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('body', models.TextField(verbose_name='Nội dung')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Story', verbose_name='Truyện')),
            ],
        ),
    ]
