# Generated by Django 3.0.8 on 2020-09-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='numberChap',
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(null=True, verbose_name='Tiểu sử tác giả'),
        ),
        migrations.AlterField(
            model_name='author',
            name='dateofBird',
            field=models.DateField(null=True, verbose_name='Năm sinh'),
        ),
        migrations.AlterField(
            model_name='author',
            name='home_town',
            field=models.TextField(max_length=300, null=True, verbose_name='Quê quán'),
        ),
    ]
